version: '3.8'
services:
  api:
    image: agustinch/mealplan-api:latest
    volumes:
      - /usr/src/app/api/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    command: yarn start
  client:
    image: agustinch/mealplan-client:latest
    volumes:
      - /usr/src/app/client/node_modules
    ports:
      - 5000:5000
    depends_on:
      - api
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - '80:80'
    depends_on:
      - api
      - client
