version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: production
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    command: yarn start
  client:
    image: agustinch/mealplan-client:latest
    volumes:
      - /usr/src/app/client/node_modules
      - ./client/.env:/usr/src/app/client/.env
    ports:
      - 5000:5000
    env_file:
      - ./client/.env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://18.231.104.17/api
    depends_on:
      - api
