name: Deploy NestJS App

on:
  push:
    branches:
      - master  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker image build -t  agustinch/mealplan-api -f ./api/Dockerfile .
          docker image build -t  agustinch/mealplan-client -f ./client/Dockerfile . 
          docker push agustinch/mealplan-api:latest
          docker push agustinch/mealplan-client:latest
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ./mealPlan
            echo $DOCKER_PASSWORD | sudo docker login -u $DOCKER_USERNAME --password-stdin
            sudo docker pull agustinch/mealplan-api:latest
            sudo docker pull agustinch/mealplan-client:latest
            sudo make up-all
